Make improvements
- You can now run `make -j8 toolchain` on Windows
- You can now run `make -j` on MacOS ARM64 and BSD OSes
- You can now use our Emacs dev environment on MacOS/Windows
- Fix bug where the x16 register was being corrupted by --ftrace
- The programs under build/bootstrap/ are updated as fat binaries
- The Makefile now explains how to download cosmocc-0.0.12 toolchain
- The build scripts under bin/ now support "cosmo" branded toolchains
- stat() now goes faster on Windows (shaves 100ms off `make` latency)
- Code cleanup and added review on the Windows signal checking code
- posix_spawnattr_setrlimit() now works around MacOS ARM64 bugs
- Landlock Make now favors posix_spawn() on non-Linux/OpenBSD
- posix_spawn() now has better --strace logging on Windows
- fstatat() can now avoid EACCES in more cases on Windows
- fchmod() can now change the readonly bit on Windows

diff --git a/bin/cosmoaddr2line b/bin/cosmoaddr2line
--- a/bin/cosmoaddr2line
+++ b/bin/cosmoaddr2line
@@ -1,15 +1,31 @@
 #!/bin/sh
+COSMO=${COSMO:-/opt/cosmo}
+
 set -- -apifCe "$@"
 
 if [ -n "$ADDR2LINE" ]; then
   exec "$ADDR2LINE" "$@"
 fi
 
-COSMO=${COSMO:-/opt/cosmo}
+find_addr2line() {
+  if [ -x o/third_party/gcc/bin/$1-linux-cosmo-addr2line ]; then
+    ADDR2LINE=o/third_party/gcc/bin/$1-linux-cosmo-addr2line
+  elif [ -x o/third_party/gcc/bin/$1-linux-musl-addr2line ]; then
+    ADDR2LINE=o/third_party/gcc/bin/$1-linux-musl-addr2line
+  elif [ -x "$COSMO/o/third_party/gcc/bin/$1-linux-cosmo-addr2line" ]; then
+    ADDR2LINE="$COSMO/o/third_party/gcc/bin/$1-linux-cosmo-addr2line"
+  elif [ -x "$COSMO/o/third_party/gcc/bin/$1-linux-musl-addr2line" ]; then
+    ADDR2LINE="$COSMO/o/third_party/gcc/bin/$1-linux-musl-addr2line"
+  else
+    echo "error: toolchain not found (try running 'cosmocc --update' or 'make' in the cosmo monorepo)" >&2
+    exit 1
+  fi
+}
+
 for ARCH in x86_64 aarch64; do
-  o/third_party/gcc/bin/$ARCH-linux-musl-addr2line "$@" 2>/dev/null && exit
-  "$COSMO/o/third_party/gcc/bin/$ARCH-linux-musl-addr2line" "$@" 2>/dev/null && exit
+  find_addr2line $ARCH
+  "$ADDR2LINE" "$@" 2>/dev/null && exit
 done
 
-echo please set the ADDR2LINE environment variable >&2
+echo "error: addr2line failed" >&2
 exit 1
diff --git a/build/objdump b/build/objdump
--- a/build/objdump
+++ b/build/objdump
@@ -1,6 +1,29 @@
 #!/bin/sh
+COSMO=${COSMO:-/opt/cosmo}
+
+if [ -n "$OBJDUMP" ]; then
+  exec "$OBJDUMP" "$@"
+fi
+
+find_objdump() {
+  if [ -x o/third_party/gcc/bin/$1-linux-cosmo-objdump ]; then
+    OBJDUMP=o/third_party/gcc/bin/$1-linux-cosmo-objdump
+  elif [ -x o/third_party/gcc/bin/$1-linux-musl-objdump ]; then
+    OBJDUMP=o/third_party/gcc/bin/$1-linux-musl-objdump
+  elif [ -x "$COSMO/o/third_party/gcc/bin/$1-linux-cosmo-objdump" ]; then
+    OBJDUMP="$COSMO/o/third_party/gcc/bin/$1-linux-cosmo-objdump"
+  elif [ -x "$COSMO/o/third_party/gcc/bin/$1-linux-musl-objdump" ]; then
+    OBJDUMP="$COSMO/o/third_party/gcc/bin/$1-linux-musl-objdump"
+  else
+    echo "error: toolchain not found (try running 'cosmocc --update' or 'make' in the cosmo monorepo)" >&2
+    exit 1
+  fi
+}
+
 if printf '%s\n' "$*" | grep aarch64 >/dev/null 2>&1; then
-  exec o/third_party/gcc/bin/aarch64-linux-musl-objdump "$@"
+  find_objdump aarch64
+  exec "$OBJDUMP" "$@"
 else
-  exec o/third_party/gcc/bin/x86_64-linux-musl-objdump "$@"
+  find_objdump x86_64
+  exec "$OBJDUMP" "$@"
 fi
